### ISSUE TITLE
Significant Energy Used 

### ISSUE THREAD

**Issue by scottdensmore** [paxos/ghNotifier-issues#23]
Not a huge deal... watching energy used on 16" MacBook Pro I see it is in the top.

![Screen Shot 2020-07-22 at 1 47 32 PM](https://user-images.githubusercontent.com/125055/88227225-23374300-cc22-11ea-9e68-01724a409dea.png)
![Screen Shot 2020-07-22 at 1 48 58 PM](https://user-images.githubusercontent.com/125055/88227236-27636080-cc22-11ea-8193-9c660c350d4c.png)

**Comment by paxos** [comment]
Interesting… I am seeing the in the Activity Monitor.

Xcode says:
<img width="1108" alt="Screenshot 2020-07-22 at 13 54 36" src="https://user-images.githubusercontent.com/121539/88227749-ed468e80-cc22-11ea-8bc6-2bb6cea6bdbd.png">

I'll keep an eye on it. Got the feeling this has something to do with the updating relative timestamps over time 🌊

**Comment by scottdensmore** [comment]
thanks

**Comment by paxos** [comment]
Found a bug caused by a retain cycle. Looks much better now:

<img width="1003" alt="Screenshot 2020-07-22 at 14 16 31" src="https://user-images.githubusercontent.com/121539/88229979-7ad7ad80-cc26-11ea-9106-d3524a662e28.png">

I think I can improve this even more in the future. Fix coming up in 0.32. 👍
